---
- name: Deploy the application
  hosts: all
  vars_files:
    - vars/main.yml
  tasks:
    - name: Remove 'app' directory
      shell: rm -rf app

    - name: Create 'app' directory
      shell: mkdir app

    - name: Copy 'env'
      copy:
        src: ../.env
        dest: app/.env

    - name: Update .env file
      lineinfile:
        path: app/.env
        line: "IMAGE_TAG={{ IMAGE_TAG }}"

    - name: Copy docker-compose-production.yml to 'app' directory
      copy:
        src: ../docker-compose-production.yml
        dest: app/docker-compose.yml

    - name: Copy 'migrations'
      copy:
        src: ../../backend/migrations/
        dest: app/migrations/

    - name: Log into DockerHub
      docker_login:
        username: "{{ DOCKER_LOGIN }}"
        password: "{{ DOCKER_PASS }}"
      no_log: true
    - name: Pull Docker images and restart containers
      shell: |
        cd app \
        && docker compose pull \
        && docker compose up --build --remove-orphans -d
