- name: "Обновление пакетов"
  hosts: all
  tasks:
    - name: роверка доступности сервера
      ansible.builtin.ping:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

- name: "Security role"
  hosts: all
  become: true
  vars_files:
    - vars/main.yml
  roles:
    - geerlingguy.security
- name: "Docker role"
  hosts: all
  become: true
  vars_files:
    - vars/main.yml
  roles:
    - geerlingguy.docker
